<?php

namespace App\Livewire\Security\AgeKey;

use App\Models\AgeKey;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Livewire\Component;

class Index extends Component
{
    use AuthorizesRequests;

    public ?string $selectedAgeKeyUuid = null;

    public ?string $generatedPrivateKey = null;

    public ?string $generatedPublicKey = null;

    public ?string $generatedName = null;

    public function getListeners(): array
    {
        return [
            'securityResourceChanged' => '$refresh',
            'ageKeyCreated' => 'refreshResources',
            'ageKeyDeleted' => 'refreshResources',
            'ageKeyUpdated' => 'refreshResources',
            'modalClosed' => 'closeEditor',
        ];
    }

    public function openEditor(string $ageKeyUuid): void
    {
        $ageKey = AgeKey::ownedByCurrentTeam()->whereUuid($ageKeyUuid)->firstOrFail();
        $this->authorize('view', $ageKey);

        $this->selectedAgeKeyUuid = $ageKey->uuid;
    }

    public function closeEditor(): void
    {
        $this->selectedAgeKeyUuid = null;
    }

    public function refreshResources(): void
    {
        $this->closeEditor();
        $this->dispatch('close-modal');
    }

    public function generateAgeKey(): void
    {
        try {
            $this->authorize('create', AgeKey::class);

            $keyPair = AgeKey::generateNewKeyPair();

            // Shown to the user exactly once — never persisted or sent back to the server.
            $this->generatedPrivateKey = $keyPair['private_key'];
            $this->generatedPublicKey = $keyPair['public_key'];
            $this->generatedName = $keyPair['name'];
        } catch (\Throwable $e) {
            $this->dispatch('error', 'Failed to generate age key: '.$e->getMessage());
        }
    }

    public function confirmGeneratedAgeKeySaved(): void
    {
        try {
            $this->authorize('create', AgeKey::class);

            if (blank($this->generatedPublicKey)) {
                return;
            }

            AgeKey::create([
                'name' => filled($this->generatedName) ? $this->generatedName : generate_random_name(),
                'description' => 'Generated by Coolify',
                'public_key' => $this->generatedPublicKey,
                'team_id' => currentTeam()->id,
            ]);

            $this->discardGeneratedAgeKey();
            $this->dispatch('success', 'Age key saved.');
        } catch (\Throwable $e) {
            $this->dispatch('error', 'Failed to save age key: '.$e->getMessage());
        }
    }

    public function discardGeneratedAgeKey(): void
    {
        $this->generatedPrivateKey = null;
        $this->generatedPublicKey = null;
        $this->generatedName = null;
    }

    public function render()
    {
        $ageKeys = AgeKey::ownedByCurrentTeam(['name', 'uuid', 'description', 'public_key', 'team_id'])->get();

        return view('livewire.security.age-key.index', [
            'ageKeys' => $ageKeys,
        ])->layout('components.layout');
    }
}
