services:
    ideploy:
        container_name: ideploy
        restart: always
        working_dir: /var/www/html
        extra_hosts:
            - host.docker.internal:host-gateway
        networks:
            - ideploy
        depends_on:
            - postgres
            - redis
            - soketi
    postgres:
        image: postgres:15-alpine
        container_name: ideploy-db
        restart: always
        networks:
            - ideploy
    redis:
        image: redis:7-alpine
        container_name: ideploy-redis
        restart: always
        networks:
            - ideploy
    soketi:
        container_name: ideploy-realtime
        extra_hosts:
            - host.docker.internal:host-gateway
        restart: always
        networks:
            - ideploy
networks:
    ideploy:
        name: ideploy
        driver: bridge
        external: false
