export interface Application {
    additional_networks_count: number;
    additional_servers_count: number;
    base_directory: string;
    build_command: string | null;
    build_pack: string;
    compose_parsing_version: string;
    config_hash: string;
    created_at: string;
    custom_docker_run_options: string | null;
    custom_healthcheck_found: boolean;
    custom_labels: string;
    custom_nginx_configuration: string;
    deleted_at: string | null;
    description?: string;
    destination_id: number;
    destination_type: string;
    docker_compose: string | null;
    docker_compose_custom_build_command: string | null;
    docker_compose_custom_start_command: string | null;
    docker_compose_domains: string | null;
    docker_compose_location: string;
    docker_compose_raw: string | null;
    docker_registry_image_name: string | null;
    docker_registry_image_tag: string | null;
    dockerfile: string | null;
    dockerfile_location: string;
    dockerfile_target_build: string | null;
    environment_id: number;
    fqdn: string;
    git_branch: string;
    git_commit_sha: string;
    git_full_url: string | null;
    git_repository: string;
    health_check_enabled: boolean;
    health_check_host: string;
    health_check_interval: number;
    health_check_method: string;
    health_check_path: string;
    health_check_port: number | null;
    health_check_response_text: string | null;
    health_check_retries: number;
    health_check_return_code: number;
    health_check_scheme: string;
    health_check_start_period: number;
    health_check_timeout: number;
    href_link: string;
    id: number;
    install_command: string | null;
    last_online_at: string;
    limits_cpu_shares: number;
    limits_cpus: string;
    limits_cpuset: string | null;
    limits_memory: string;
    limits_memory_reservation: string;
    limits_memory_swap: string;
    limits_memory_swappiness: number;
    manual_webhook_secret_bitbucket: string | null;
    manual_webhook_secret_gitea: string | null;
    manual_webhook_secret_github: string | null;
    manual_webhook_secret_gitlab: string | null;
    name: string;
    ports_exposes: string;
    ports_mappings: string | null;
    post_deployment_command: string | null;
    post_deployment_command_container: string | null;
    pre_deployment_command: string | null;
    pre_deployment_command_container: string | null;
    preview_url_template: string;
    private_key_id: number | null;
    publish_directory: string;
    redirect: string;
    repository_project_id: number | null;
    source_id: number;
    source_type: string;
    start_command: string | null;
    static_image: string;
    status: string;
    swarm_placement_constraints: string | null;
    swarm_replicas: number;
    updated_at: string;
    uuid: string;
    watch_paths: string | null;
}
