export interface Mongodb {
    config_hash: string | null;
    created_at: string;
    custom_docker_run_options: string | null;
    deleted_at: string | null;
    description: string | null;
    destination_id: number;
    destination_type: string;
    environment_id: number;
    hrefLink: string;
    id: number;
    image: string;
    is_include_timestamps: boolean;
    is_log_drain_enabled: boolean;
    is_public: boolean;
    last_online_at: string;
    limits_cpu_shares: number;
    limits_cpus: string;
    limits_cpuset: string | null;
    limits_memory: string;
    limits_memory_reservation: string;
    limits_memory_swap: string;
    limits_memory_swappiness: number;
    mongo_conf: string | null;
    mongo_initdb_database: string;
    mongo_initdb_root_password: string;
    mongo_initdb_root_username: string;
    name: string;
    ports_mappings: string | null;
    public_port: number | null;
    started_at: string | null;
    status: string;
    updated_at: string;
    uuid: string;
}
