import node from './node'
import staticApp from './static'
import docker from './docker'
import gatsby from './gatsby'
import svelte from './svelte'
import react from './react'
import nestjs from './nestjs'
import nextjs from './nextjs'
import nuxtjs from './nuxtjs'
import vue from './vue'
export { node, staticApp as static, docker, gatsby, svelte, react, nestjs, nextjs, nuxtjs, vue }