services:
    coolify:
        container_name: coolify
        restart: always
        working_dir: /var/www/html
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - coolify
        depends_on:
            - postgres
            - redis
            - soketi
    postgres:
        image: postgres:15-alpine
        container_name: coolify-db
        restart: always
        networks:
            - coolify

    pgbackrest:
        image: pogryzov/pgbackrest:2
        container_name: coolify-pgbackrest
        restart: always
        networks:
            - coolify
        volumes:
            - coolify-db:/var/lib/postgresql/data
            - ./pgbackrest-repo:/var/lib/pgbackrest
        environment:
            - PGBACKREST_REPO1_PATH=/var/lib/pgbackrest
            - PGBACKREST_REPO1_RETENTION_FULL=2
            - PGBACKREST_REPO1_RETENTION_DIFF=6
            - PGBACKREST_STANZA=main
    redis:
        image: redis:alpine
        container_name: coolify-redis
        restart: always
        networks:
            - coolify
    soketi:
        container_name: coolify-realtime
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        restart: always
        networks:
            - coolify
networks:
    coolify:
        name: coolify
        driver: bridge
        external: false

volumes:
    pgbackrest-repo:
