<?php

namespace App\Livewire\Server\Proxy;

use App\Enums\ProxyTypes;
use App\Models\Server;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Support\Collection;
use Livewire\Component;
use Symfony\Component\Yaml\Yaml;

class Gateway extends Component
{
    use AuthorizesRequests;

    public const MANAGED_FILE_MARKER = '# This file is generated by Coolify, do not edit it manually.';

    public const DOMAIN_REGEX = '/^(\*\.)?[A-Za-z0-9\-_]+(\.[A-Za-z0-9\-_]+)+$/';

    public ?Server $server = null;

    public $parameters = [];

    public Collection $routes;

    public Collection $brokenFiles;

    public bool $loading = false;

    public ?bool $dnsChallengeMissing = null;

    protected $listeners = ['gatewayRoutesSaved' => 'loadRoutes'];

    public function mount()
    {
        $this->parameters = get_route_parameters();
        try {
            $this->server = Server::ownedByCurrentTeam()->whereUuid(request()->server_uuid)->first();
            if (is_null($this->server)) {
                return redirect()->route('server.index');
            }
            if ($this->server->proxyType() !== ProxyTypes::TRAEFIK->value) {
                return redirect()->route('server.proxy', ['server_uuid' => $this->server->uuid]);
            }
            $this->routes = collect();
            $this->brokenFiles = collect();
        } catch (\Throwable $e) {
            return handleError($e, $this);
        }
    }

    public function initLoadRoutes()
    {
        $this->loadRoutes();
    }

    public function loadRoutes()
    {
        try {
            $this->loading = true;
            $this->checkDnsChallenge();
            $routes = [];
            $broken = [];
            foreach (self::listRouteFiles($this->server) as $file) {
                try {
                    $config = self::readRouteFile($this->server, $file);
                    $routes = array_merge($routes, self::parseRoutes($config, $file));
                } catch (\Throwable $e) {
                    $broken[] = ['file' => $file, 'error' => $e->getMessage()];
                }
            }
            $byFile = collect($routes)->groupBy('source_file');
            $this->routes = collect($routes)
                ->map(fn ($r) => $r + ['is_only_in_file' => $byFile[$r['source_file']]->count() === 1])
                ->sortBy('name')
                ->values();
            $this->brokenFiles = collect($broken)->sortBy('file')->values();
        } catch (\Throwable $e) {
            return handleError($e, $this);
        } finally {
            $this->loading = false;
        }
    }

    private function checkDnsChallenge(): void
    {
        $file = escapeshellarg($this->server->proxyPath().'/docker-compose.yml');
        $contents = instant_remote_process(
            ["test -f {$file} && cat {$file} || echo ''"],
            $this->server,
            throwError: false,
        );
        $this->dnsChallengeMissing = ! str_contains(strtolower($contents ?? ''), 'dnschallenge=true');
    }

    public function deleteRoute(string $routerName, string $password = '')
    {
        try {
            $this->authorize('update', $this->server);
            $route = self::findRoute($this->server, $routerName);
            if (! $route) {
                $this->dispatch('error', 'Gateway route not found.');

                return;
            }
            self::removeRouterFromFile($this->server, $route['source_file'], $routerName);
            $this->loadRoutes();
            $this->dispatch('success', 'Gateway route deleted.');
        } catch (\Throwable $e) {
            return handleError($e, $this);
        }
    }

    public function deleteBrokenFile(string $file, string $password = '')
    {
        try {
            $this->authorize('update', $this->server);
            if (dirname($file) !== self::gatewayDirPath($this->server)
                || ! preg_match('/^gateway-[A-Za-z0-9._\-]+\.yaml$/', basename($file))) {
                $this->dispatch('error', 'Invalid gateway file path.');

                return;
            }
            self::deleteFile($this->server, $file);
            $this->loadRoutes();
            $this->dispatch('success', 'Broken gateway file deleted.');
        } catch (\Throwable $e) {
            return handleError($e, $this);
        }
    }

    public static function findRoute(Server $server, string $routerName): ?array
    {
        foreach (self::listRouteFiles($server) as $file) {
            try {
                $config = self::readRouteFile($server, $file);
                foreach (self::parseRoutes($config, $file) as $route) {
                    if ($route['router_name'] === $routerName) {
                        return $route;
                    }
                }
            } catch (\Throwable) {
                // Skip files we can't parse; surfaced as broken in loadRoutes.
            }
        }

        return null;
    }

    public static function removeRouterFromFile(Server $server, string $file, string $routerName): void
    {
        $config = self::readRouteFile($server, $file);
        $config = self::stripRouter($config, $routerName);

        $remaining = $config['http']['routers'] ?? [];
        if (empty($remaining)) {
            self::deleteFile($server, $file);
        } else {
            self::writeFile($server, $file, $config);
        }
    }

    public static function stripRouter(array $config, string $routerName): array
    {
        $routers = $config['http']['routers'] ?? [];

        $toRemove = [$routerName];
        if (isset($routers["{$routerName}-http"])) {
            $toRemove[] = "{$routerName}-http";
        }

        foreach ($toRemove as $r) {
            unset($config['http']['routers'][$r]);
        }
        unset($config['http']['services'][$routerName]);
        foreach (['stripprefix', 'redirect'] as $suffix) {
            unset($config['http']['middlewares']["{$routerName}-{$suffix}"]);
        }
        if (isset($config['http']['middlewares']) && empty($config['http']['middlewares'])) {
            unset($config['http']['middlewares']);
        }

        return $config;
    }

    public static function gatewayDirPath(Server $server): string
    {
        return $server->proxyPath().'/dynamic';
    }

    public static function routeFilePath(Server $server, string $routerName): string
    {
        self::assertValidRouterName($routerName);

        return self::gatewayDirPath($server)."/{$routerName}.yaml";
    }

    private static function assertValidRouterName(string $routerName): void
    {
        if (! preg_match('/^gateway-[a-z0-9-]+$/', $routerName)) {
            throw new \InvalidArgumentException('Invalid gateway route name.');
        }
    }

    public static function listRouteFiles(Server $server): array
    {
        $dir = escapeshellarg(self::gatewayDirPath($server));
        $marker = escapeshellarg(self::MANAGED_FILE_MARKER);
        $output = instant_remote_process(
            ["grep -l -F {$marker} {$dir}/gateway-*.yaml 2>/dev/null || true"],
            $server,
            throwError: false,
        );

        return collect(preg_split('/\r?\n/', $output ?? ''))
            ->map(fn ($s) => trim($s))
            ->filter()
            ->values()
            ->all();
    }

    public static function fileExistsAt(Server $server, string $path): bool
    {
        $escaped = escapeshellarg($path);
        $output = instant_remote_process(
            ["test -f {$escaped} && echo 1 || echo 0"],
            $server,
            throwError: false,
        );

        return trim($output ?? '') === '1';
    }

    public static function readRouteFile(Server $server, string $file): array
    {
        $escapedFile = escapeshellarg($file);
        $contents = instant_remote_process(
            ["test -f {$escapedFile} && cat {$escapedFile} || echo ''"],
            $server,
            throwError: false,
        );
        if (empty(trim($contents ?? ''))) {
            return [];
        }
        $parsed = Yaml::parse($contents);

        return is_array($parsed) ? $parsed : [];
    }

    public static function writeFile(Server $server, string $file, array $config): void
    {
        $escapedFile = escapeshellarg($file);
        $dir = escapeshellarg(dirname($file));
        $header = <<<YAML
            # This file is generated by Coolify, do not edit it manually.
            # Remove the route from UI first to customize (only if you know what are you doing).
            # Changes done from UI will overwrite this file.


            YAML;
        // Keep the first line in sync with self::MANAGED_FILE_MARKER so listRouteFiles() recognizes it.
        $yaml = $header.Yaml::dump($config, 10, 2);
        $base64 = base64_encode($yaml);
        instant_remote_process([
            "mkdir -p {$dir}",
            "echo '{$base64}' | base64 -d | tee {$escapedFile} > /dev/null",
        ], $server);
    }

    public static function deleteFile(Server $server, string $file): void
    {
        $escapedFile = escapeshellarg($file);
        instant_remote_process(["rm -f {$escapedFile}"], $server);
    }

    public static function parseRoutes(array $config, ?string $sourceFile = null): array
    {
        $http = $config['http'] ?? [];
        if (! is_array($http)) {
            return [];
        }
        $routers = is_array($http['routers'] ?? null) ? $http['routers'] : [];
        $services = is_array($http['services'] ?? null) ? $http['services'] : [];
        $middlewares = is_array($http['middlewares'] ?? null) ? $http['middlewares'] : [];
        $routes = [];

        foreach ($routers as $name => $router) {
            // Skip the auto-generated HTTP redirect router; we surface it via the parent route.
            if (str_ends_with($name, '-http') && isset($routers[substr($name, 0, -5)])) {
                continue;
            }
            if (! is_array($router)) {
                continue;
            }

            $rule = $router['rule'] ?? '';
            $domain = '';
            $pathPrefix = '/';

            if (preg_match('/Host\(`([^`]+)`\)/', $rule, $m)) {
                $domain = $m[1];
            } elseif (preg_match('/HostRegexp\(`([^`]+)`\)/', $rule, $m)) {
                $pattern = $m[1];
                $prefix = '^[a-zA-Z0-9-]+\\.';
                if (str_starts_with($pattern, $prefix) && str_ends_with($pattern, '$')) {
                    $base = substr($pattern, strlen($prefix), -1);
                    $domain = '*.'.str_replace('\\.', '.', $base);
                }
            }
            if (preg_match('/PathPrefix\(`([^`]+)`\)/', $rule, $m)) {
                $pathPrefix = $m[1];
            }

            $serviceName = $router['service'] ?? null;
            $service = $serviceName ? ($services[$serviceName] ?? null) : null;
            $targetUrlRaw = $service['loadBalancer']['servers'][0]['url'] ?? '';
            $targetUrl = is_string($targetUrlRaw) ? $targetUrlRaw : '';
            $isValidTargetUrl = $targetUrl !== ''
                && filter_var($targetUrl, FILTER_VALIDATE_URL) !== false
                && in_array(parse_url($targetUrl, PHP_URL_SCHEME), ['http', 'https'], true);
            // Traefik defaults passHostHeader to true when omitted; preserve that behavior when parsing.
            $lb = is_array($service['loadBalancer'] ?? null) ? $service['loadBalancer'] : null;
            $passHostHeaderPresent = $lb !== null && array_key_exists('passHostHeader', $lb);
            $passHostHeaderRaw = $passHostHeaderPresent ? $lb['passHostHeader'] : true;
            $passHostHeader = $passHostHeaderRaw === true;

            $routerMiddlewares = is_array($router['middlewares'] ?? null) ? $router['middlewares'] : [];
            $stripPrefix = false;
            foreach ($routerMiddlewares as $mw) {
                if (is_string($mw) && str_ends_with($mw, '-stripprefix')) {
                    $stripPrefix = true;
                }
            }

            $entrypointsPresent = array_key_exists('entryPoints', $router);
            $entrypoints = is_array($router['entryPoints'] ?? null) ? $router['entryPoints'] : [];

            $isValidDomain = $domain !== ''
                && strlen($domain) <= 255
                && preg_match(self::DOMAIN_REGEX, $domain) === 1;

            $missingFields = [];
            if (! $isValidDomain) {
                $missingFields[] = 'domain';
            }
            if (! $isValidTargetUrl) {
                $missingFields[] = 'target_url';
            }
            // Traefik treats an omitted entryPoints as "all default entrypoints"; saving from the UI would
            // narrow that to the form value, so flag it as missing and require the user to be explicit.
            if (! $entrypointsPresent || empty($entrypoints)) {
                $missingFields[] = 'entrypoints';
            }
            if ($passHostHeaderPresent && ! is_bool($lb['passHostHeader'])) {
                $missingFields[] = 'pass_host_header';
            }

            $routes[] = [
                'router_name' => $name,
                'name' => preg_replace('/^gateway-/', '', $name),
                'source_file' => $sourceFile ?? '',
                'domain' => $domain,
                'path_prefix' => $pathPrefix,
                'target_url' => $targetUrl,
                'entrypoints' => $entrypoints,
                'tls_enabled' => isset($router['tls']),
                'tls_cert_resolver' => is_array($router['tls'] ?? null) ? ($router['tls']['certResolver'] ?? '') : '',
                'pass_host_header' => $passHostHeader,
                'https_redirect' => isset($routers["{$name}-http"]),
                'strip_prefix' => $stripPrefix,
                'has_extra_config' => self::detectExtraConfig($name, $router, $service, $middlewares, $config, $routers),
                'missing_fields' => $missingFields,
            ];
        }

        return $routes;
    }

    private static function detectExtraConfig(string $name, array $router, ?array $service, array $middlewares, array $config, array $routers = []): bool
    {
        $knownRouterKeys = ['rule', 'entryPoints', 'service', 'tls', 'middlewares'];
        if (count(array_diff(array_keys($router), $knownRouterKeys)) > 0) {
            return true;
        }

        if (isset($router['tls']) && is_array($router['tls'])) {
            $knownTlsKeys = ['certResolver'];
            if (count(array_diff(array_keys($router['tls']), $knownTlsKeys)) > 0) {
                return true;
            }
        }

        $routerMiddlewares = $router['middlewares'] ?? [];
        if (! is_array($routerMiddlewares)) {
            return true;
        }
        foreach ($routerMiddlewares as $mw) {
            if (! is_string($mw)) {
                return true;
            }
            if (! str_ends_with($mw, '-stripprefix') && ! str_ends_with($mw, '-redirect')) {
                return true;
            }
            if (! self::middlewareBodyMatchesUiShape($mw, $middlewares[$mw] ?? null)) {
                return true;
            }
        }

        // Inspect the auto-generated HTTP redirect router's middleware body if present.
        $httpRedirectRouter = $routers["{$name}-http"] ?? null;
        if (is_array($httpRedirectRouter)) {
            $redirectMiddlewares = $httpRedirectRouter['middlewares'] ?? [];
            if (is_array($redirectMiddlewares)) {
                foreach ($redirectMiddlewares as $mw) {
                    if (is_string($mw) && str_ends_with($mw, '-redirect')
                        && ! self::middlewareBodyMatchesUiShape($mw, $middlewares[$mw] ?? null)) {
                        return true;
                    }
                }
            }
        }

        if ($service !== null) {
            $lb = $service['loadBalancer'] ?? null;
            if ($lb === null) {
                return true;
            }
            $knownLbKeys = ['passHostHeader', 'servers'];
            if (count(array_diff(array_keys($lb), $knownLbKeys)) > 0) {
                return true;
            }
            $servers = $lb['servers'] ?? [];
            if (count($servers) > 1) {
                return true;
            }
            if (isset($servers[0]) && is_array($servers[0]) && count(array_diff(array_keys($servers[0]), ['url'])) > 0) {
                return true;
            }
        }

        if (count(array_diff(array_keys($config), ['http'])) > 0) {
            return true;
        }
        if (isset($config['http']) && is_array($config['http'])) {
            if (count(array_diff(array_keys($config['http']), ['routers', 'services', 'middlewares'])) > 0) {
                return true;
            }
        }

        return false;
    }

    private static function middlewareBodyMatchesUiShape(string $middlewareName, mixed $body): bool
    {
        if (! is_array($body)) {
            return false;
        }

        if (str_ends_with($middlewareName, '-stripprefix')) {
            if (array_keys($body) !== ['stripPrefix']) {
                return false;
            }
            $sp = $body['stripPrefix'];
            if (! is_array($sp) || array_keys($sp) !== ['prefixes']) {
                return false;
            }
            if (! is_array($sp['prefixes'])) {
                return false;
            }
            foreach ($sp['prefixes'] as $prefix) {
                if (! is_string($prefix)) {
                    return false;
                }
            }

            return true;
        }

        if (str_ends_with($middlewareName, '-redirect')) {
            if (array_keys($body) !== ['redirectScheme']) {
                return false;
            }
            $rs = $body['redirectScheme'];
            if (! is_array($rs) || array_keys($rs) !== ['scheme']) {
                return false;
            }

            return $rs['scheme'] === 'https';
        }

        return false;
    }

    public function render()
    {
        return view('livewire.server.proxy.gateway');
    }
}
