<?php

namespace App\Actions\C3;

use App\Enums\ProxyTypes;
use App\Models\Project;
use App\Models\Server;
use Lorisleiva\Actions\Concerns\AsAction;
use Symfony\Component\Yaml\Yaml;

/**
 * Connect3 fork: writes (or removes) "dynamic/c3_<slug>.yaml" for one project. The file holds
 * the project's basic-auth middleware and, when live, the routers for its client domains.
 * Only the proxy's file provider changes: no container is touched (PRD section 4.3).
 */
class SyncProjectProxyConfig
{
    use AsAction;

    public function handle(Project $project, ?string $previousSlug = null, bool $remove = false): void
    {
        $server = Server::find(0);
        if (! $server || $server->proxyType() !== ProxyTypes::TRAEFIK->value) {
            return;
        }
        $dynamicPath = rtrim($server->proxyPath(), '/').'/dynamic';
        $commands = [];

        if ($previousSlug && $previousSlug !== $project->client_slug) {
            $commands[] = "rm -f {$dynamicPath}/".c3_dynamicFileName($previousSlug);
        }

        $slug = $project->client_slug;
        if ($remove || blank($slug) || ! c3_enabled()) {
            if (filled($slug)) {
                $commands[] = "rm -f {$dynamicPath}/".c3_dynamicFileName($slug);
            }
            if ($commands !== []) {
                instant_remote_process($commands, $server, false);
            }

            return;
        }

        $yaml = "# Generated by Coolify (Connect3 fork) for project '{$project->name}'. Do not edit.\n\n"
            .Yaml::dump($project->c3DynamicConfig(), 12, 2);
        $commands[] = "mkdir -p {$dynamicPath}";
        $commands[] = "echo '".base64_encode($yaml)."' | base64 -d | tee {$dynamicPath}/".c3_dynamicFileName($slug).' > /dev/null';
        instant_remote_process($commands, $server);
    }
}
