<?php

namespace App\Actions\C3;

use App\Enums\ProxyTypes;
use App\Models\Server;
use Lorisleiva\Actions\Concerns\AsAction;
use Symfony\Component\Yaml\Yaml;

/**
 * Connect3 fork: writes (or removes) the shared Traefik file-provider config
 * "dynamic/c3_global.yaml" and the Cloudflare DNS-01 token file on the localhost server.
 */
class SyncGlobalProxyConfig
{
    use AsAction;

    public function handle(?Server $server = null): void
    {
        $server ??= Server::find(0);
        if (! $server || $server->proxyType() !== ProxyTypes::TRAEFIK->value) {
            return;
        }
        $proxyPath = rtrim($server->proxyPath(), '/');
        $dynamicPath = "{$proxyPath}/dynamic";
        $file = "{$dynamicPath}/c3_global.yaml";
        $tokenFile = "{$proxyPath}/".C3_CLOUDFLARE_TOKEN_FILE;

        $apex = c3_stagingApex();
        if (! $apex) {
            instant_remote_process(["rm -f {$file}", "rm -f {$tokenFile}"], $server, false);

            return;
        }

        $hasToken = c3_hasCloudflareToken();
        $config = c3_globalDynamicConfig($apex, c3_stagingCertResolver(), $hasToken);
        $yaml = "# Generated by Coolify (Connect3 fork). Do not edit; it is rewritten on every settings change.\n\n"
            .Yaml::dump($config, 12, 2);
        $commands = [
            "mkdir -p {$dynamicPath}",
            "echo '".base64_encode($yaml)."' | base64 -d | tee {$file} > /dev/null",
        ];
        if ($hasToken) {
            $token = (string) data_get(instanceSettings(), 'c3_cloudflare_dns_token');
            $commands[] = "umask 077 && echo '".base64_encode($token)."' | base64 -d > {$tokenFile}";
            $commands[] = "chmod 600 {$tokenFile}";
        } else {
            $commands[] = "rm -f {$tokenFile}";
        }
        instant_remote_process($commands, $server);
    }
}
