# documentation: https://docs.appflowy.io/docs/cloud/self-hosting/docker-compose
# slogan: The Open-Source, AI-Powered Workspace. A privacy-first alternative to Notion.
# tags: appflowy,notion,open-source,productivity,notes,ai,self-hosted
# logo: svgs/appflowy.svg
# port: 80

services:
  nginx:
    image: nginx:latest
    environment:
      # This is the only FQDN needed. Coolify's Traefik proxy will forward all traffic
      # for your domain to this Nginx container on port 80.
      - SERVICE_FQDN_APP=/
    volumes:
      - type: bind
        source: ./nginx.conf # This name is a reference for Coolify
        target: /etc/nginx/conf.d/default.conf
        content: |
          map $http_upgrade $connection_upgrade {
              default upgrade;
              ''      close;
          }

          server {
              listen 80;
              server_name _;
              underscores_in_headers on;

              # GoTrue Authentication
              location /gotrue/ {
                  proxy_pass http://gotrue:9999;
                  rewrite ^/gotrue(/.*)$ $1 break;
                  proxy_set_header Host $http_host;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_pass_request_headers on;
              }

              # WebSocket for real-time collaboration
              location /ws {
                  proxy_pass http://appflowy_cloud:8000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "Upgrade";
                  proxy_set_header Host $host;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_read_timeout 86400s;
              }

              # Main API
              location /api {
                  proxy_pass http://appflowy_cloud:8000;
                  proxy_set_header X-Request-Id $request_id;
                  proxy_set_header Host $http_host;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;

                  location ~* ^/api/workspace/([a-zA-Z0-9_-]+)/publish$ {
                      proxy_pass http://appflowy_cloud:8000;
                      proxy_request_buffering off;
                      client_max_body_size 256M;
                  }
                  location /api/chat {
                      proxy_pass http://appflowy_cloud:8000;
                      proxy_http_version 1.1;
                      proxy_set_header Connection "";
                      chunked_transfer_encoding on;
                      proxy_buffering off;
                      proxy_cache off;
                      proxy_read_timeout 600s;
                      proxy_connect_timeout 600s;
                      proxy_send_timeout 600s;
                  }
                  location /api/import {
                      proxy_pass http://appflowy_cloud:8000;
                      proxy_set_header X-Request-Id $request_id;
                      proxy_set_header Host $http_host;
                      proxy_read_timeout 600s;
                      proxy_connect_timeout 600s;
                      proxy_send_timeout 600s;
                      proxy_request_buffering off;
                      proxy_buffering off;
                      proxy_cache off;
                      client_max_body_size 2G;
                  }
              }

              # Minio Web UI Console
              location /minio/ {
                  proxy_pass http://minio:9001;
                  rewrite ^/minio/(.*) /$1 break;
                  proxy_set_header Host $http_host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_set_header X-NginX-Proxy true;
                  real_ip_header X-Real-IP;
                  proxy_connect_timeout 300s;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "upgrade";
                  chunked_transfer_encoding off;
              }

              # Minio API for pre-signed URLs
              location /minio-api/ {
                  proxy_pass http://minio:9000;
                  rewrite ^/minio-api/(.*) /$1 break;
                  # The Host header must be the internal hostname for presigned URLs to work
                  proxy_set_header Host minio:9000;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_connect_timeout 300s;
                  proxy_http_version 1.1;
                  proxy_set_header Connection "";
                  chunked_transfer_encoding off;
              }

              # Admin Frontend Console
              location /console {
                  proxy_pass http://admin_frontend:3001;
                  proxy_set_header Host $host;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }

              # AppFlowy Web Interface (Catch-all)
              location / {
                  proxy_pass http://appflowy_web:80;
                  proxy_set_header Host $host;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
    depends_on:
      - appflowy_web
      - admin_frontend
      - appflowy_cloud
      - minio
      - gotrue

  appflowy_web:
    image: appflowyinc/appflowy_web:${APPFLOWY_WEB_VERSION:-latest}
    depends_on:
      - appflowy_cloud

  appflowy_cloud:
    image: appflowyinc/appflowy_cloud:${APPFLOWY_CLOUD_VERSION:-latest}
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - APPFLOWY_ENVIRONMENT=production
      - APPFLOWY_DATABASE_URL=postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/${POSTGRES_DB:-appflowy}
      - APPFLOWY_REDIS_URI=redis://redis:6379
      - APPFLOWY_GOTRUE_JWT_SECRET=${SERVICE_PASSWORD_JWT}
      - APPFLOWY_GOTRUE_JWT_EXP=${GOTRUE_JWT_EXP:-7200}
      - APPFLOWY_GOTRUE_BASE_URL=http://gotrue:9999
      - APPFLOWY_S3_CREATE_BUCKET=${APPFLOWY_S3_CREATE_BUCKET:-true}
      - APPFLOWY_S3_USE_MINIO=true
      - APPFLOWY_S3_MINIO_URL=http://minio:9000
      - APPFLOWY_S3_ACCESS_KEY=${SERVICE_USER_MINIO}
      - APPFLOWY_S3_SECRET_KEY=${SERVICE_PASSWORD_MINIO}
      - APPFLOWY_S3_BUCKET=${APPFLOWY_S3_BUCKET:-appflowy}
      - APPFLOWY_S3_REGION=${APPFLOWY_S3_REGION:-us-east-1}
      - APPFLOWY_S3_PRESIGNED_URL_ENDPOINT=${SERVICE_FQDN_APP}/minio-api
      - APPFLOWY_MAILER_SMTP_HOST=${APPFLOWY_MAILER_SMTP_HOST}
      - APPFLOWY_MAILER_SMTP_PORT=${APPFLOWY_MAILER_SMTP_PORT:-587}
      - APPFLOWY_MAILER_SMTP_USERNAME=${APPFLOWY_MAILER_SMTP_USERNAME}
      - APPFLOWY_MAILER_SMTP_EMAIL=${APPFLOWY_MAILER_SMTP_EMAIL}
      - APPFLOWY_MAILER_SMTP_PASSWORD=${APPFLOWY_MAILER_SMTP_PASSWORD}
      - APPFLOWY_MAILER_SMTP_TLS_KIND=${APPFLOWY_MAILER_SMTP_TLS_KIND:-none}
      - APPFLOWY_ACCESS_CONTROL=true
      - APPFLOWY_DATABASE_MAX_CONNECTIONS=40
      - AI_SERVER_HOST=ai
      - AI_SERVER_PORT=5001
      - AI_OPENAI_API_KEY=${AI_OPENAI_API_KEY:-}
      - APPFLOWY_WEB_URL=${SERVICE_FQDN_APP}
    depends_on:
      gotrue:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  gotrue:
    image: appflowyinc/gotrue:${GOTRUE_VERSION:-latest}
    environment:
      - GOTRUE_API_HOST=0.0.0.0
      - GOTRUE_API_PORT=9999
      - GOTRUE_ADMIN_EMAIL=${GOTRUE_ADMIN_EMAIL:-admin@example.com}
      - GOTRUE_ADMIN_PASSWORD=${SERVICE_PASSWORD_ADMIN}
      - GOTRUE_DISABLE_SIGNUP=false
      - GOTRUE_SITE_URL=appflowy-flutter://
      - GOTRUE_URI_ALLOW_LIST=**
      - GOTRUE_JWT_SECRET=${SERVICE_PASSWORD_JWT}
      - GOTRUE_JWT_EXP=${GOTRUE_JWT_EXP:-7200}
      - GOTRUE_JWT_ADMIN_GROUP_NAME=supabase_admin
      - GOTRUE_DB_DRIVER=postgres
      - API_EXTERNAL_URL=${SERVICE_FQDN_APP}/gotrue
      - DATABASE_URL=postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/${POSTGRES_DB:-appflowy}?search_path=auth
      - GOTRUE_SMTP_HOST=${GOTRUE_SMTP_HOST}
      - GOTRUE_SMTP_PORT=${GOTRUE_SMTP_PORT:-587}
      - GOTRUE_SMTP_USER=${GOTRUE_SMTP_USER}
      - GOTRUE_SMTP_PASS=${GOTRUE_SMTP_PASS}
      - GOTRUE_MAILER_URLPATHS_CONFIRMATION=/verify
      - GOTRUE_MAILER_URLPATHS_INVITE=/verify
      - GOTRUE_MAILER_URLPATHS_RECOVERY=/verify
      - GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE=/verify
      - GOTRUE_SMTP_ADMIN_EMAIL=${GOTRUE_SMTP_ADMIN_EMAIL}
      - GOTRUE_SMTP_MAX_FREQUENCY=1ns
      - GOTRUE_RATE_LIMIT_EMAIL_SENT=100
      - GOTRUE_MAILER_AUTOCONFIRM=true
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: "curl --fail http://127.0.0.1:9999/health || exit 1"
      interval: 5s
      timeout: 5s
      retries: 12

  admin_frontend:
    image: appflowyinc/admin_frontend:${APPFLOWY_ADMIN_FRONTEND_VERSION:-latest}
    environment:
      - RUST_LOG=info
      - ADMIN_FRONTEND_REDIS_URL=redis://redis:6379
      - ADMIN_FRONTEND_GOTRUE_URL=http://gotrue:9999
      - ADMIN_FRONTEND_APPFLOWY_CLOUD_URL=http://appflowy_cloud:8000
      - ADMIN_FRONTEND_OAUTH_CLIENT_SECRET=${SERVICE_PASSWORD_ADMINOAUTH}
      - ADMIN_FRONTEND_OAUTH_ALLOWABLE_REDIRECT_URIS=${SERVICE_FQDN_APP}/console
      - ADMIN_FRONTEND_PATH_PREFIX=/console
      - ADMIN_FRONTEND_HOST=0.0.0.0
      - ADMIN_FRONTEND_PORT=3001
      - ADMIN_FRONTEND_OAUTH_CLIENT_ID=appflowy_cloud
    depends_on:
      gotrue:
        condition: service_healthy
      appflowy_cloud:
        condition: service_started

  ai:
    image: appflowyinc/appflowy_ai:${APPFLOWY_AI_VERSION:-latest}
    environment:
      - OPENAI_API_KEY=${AI_OPENAI_API_KEY:-}
      - APPFLOWY_AI_SERVER_PORT=5001
      - APPFLOWY_AI_DATABASE_URL=postgresql+psycopg://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/${POSTGRES_DB:-appflowy}
      - APPFLOWY_AI_REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy

  appflowy_worker:
    image: appflowyinc/appflowy_worker:${APPFLOWY_WORKER_VERSION:-latest}
    environment:
      - RUST_LOG=info
      - APPFLOWY_ENVIRONMENT=production
      - APPFLOWY_WORKER_REDIS_URL=redis://redis:6379
      - APPFLOWY_WORKER_DATABASE_URL=postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/${POSTGRES_DB:-appflowy}
      - APPFLOWY_WORKER_DATABASE_NAME=${POSTGRES_DB:-appflowy}
      - APPFLOWY_WORKER_IMPORT_TICK_INTERVAL=30
      - APPFLOWY_S3_USE_MINIO=true
      - APPFLOWY_S3_MINIO_URL=http://minio:9000
      - APPFLOWY_S3_ACCESS_KEY=${SERVICE_USER_MINIO}
      - APPFLOWY_S3_SECRET_KEY=${SERVICE_PASSWORD_MINIO}
      - APPFLOWY_S3_BUCKET=${APPFLOWY_S3_BUCKET:-appflowy}
      - APPFLOWY_S3_REGION=${APPFLOWY_S3_REGION:-us-east-1}
      - APPFLOWY_MAILER_SMTP_HOST=${APPFLOWY_MAILER_SMTP_HOST}
      - APPFLOWY_MAILER_SMTP_PORT=${APPFLOWY_MAILER_SMTP_PORT:-587}
      - APPFLOWY_MAILER_SMTP_USERNAME=${APPFLOWY_MAILER_SMTP_USERNAME}
      - APPFLOWY_MAILER_SMTP_EMAIL=${APPFLOWY_MAILER_SMTP_EMAIL}
      - APPFLOWY_MAILER_SMTP_PASSWORD=${APPFLOWY_MAILER_SMTP_PASSWORD}
      - APPFLOWY_MAILER_SMTP_TLS_KIND=${APPFLOWY_MAILER_SMTP_TLS_KIND:-none}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=${SERVICE_USER_MINIO}
      - MINIO_ROOT_PASSWORD=${SERVICE_PASSWORD_MINIO}
      - MINIO_BROWSER_REDIRECT_URL=${SERVICE_FQDN_APP}/minio
    command: server /data --console-address ":9001"
    volumes:
      # Coolify will manage this named volume for persistent object storage.
      - minio_data:/data

  postgres:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_USER=${SERVICE_USER_POSTGRES}
      - POSTGRES_DB=${POSTGRES_DB:-appflowy}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
      - POSTGRES_HOST=postgres
    volumes:
      # Coolify will manage this named volume for persistent database storage.
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${SERVICE_USER_POSTGRES}", "-d", "${POSTGRES_DB:-appflowy}" ]
      interval: 5s
      timeout: 5s
      retries: 12

  redis:
    image: redis

# These named volumes will be created and managed by Docker/Coolify.
volumes:
  postgres_data:
  minio_data:
