# documentation: https://github.com/bluesky-social/pds
# slogan: Bluesky PDS (Personal Data Server) container image, compose file, and documentation
# tags: bluesky, pds, platform
# logo: svgs/bluesky.svg

services:
  pds:
    image: 'ghcr.io/bluesky-social/pds:0.4.158'
    environment:
      - PDS_HOSTNAME=${PDS_HOSTNAME}
      - PDS_JWT_SECRET=${SERVICE_PASSWORD_JWT_SECRET}
      - PDS_ADMIN_PASSWORD=${SERVICE_PASSWORD_ADMIN}
      - PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX=${PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX}
      - PDS_DATA_DIRECTORY=/pds
      - PDS_BLOBSTORE_DISK_LOCATION=/pds/blocks
      - PDS_BLOB_UPLOAD_LIMIT=${PDS_BLOB_UPLOAD_LIMIT:-52428800}
      - PDS_DID_PLC_URL=${PDS_DID_PLC_URL:-https://plc.directory}
      - PDS_BSKY_APP_VIEW_URL=${PDS_BSKY_APP_VIEW_URL:-https://api.bsky.app}
      - PDS_BSKY_APP_VIEW_DID=${PDS_BSKY_APP_VIEW_DID:-did:web:api.bsky.app}
      - PDS_REPORT_SERVICE_URL=${PDS_REPORT_SERVICE_URL:-https://mod.bsky.app/xrpc/com.atproto.moderation.createReport}
      - PDS_REPORT_SERVICE_DID=${PDS_REPORT_SERVICE_DID:-did:plc:ar7c4by46qjdydhdevvrndac}
      - PDS_CRAWLERS=${PDS_CRAWLERS:-https://bsky.network}
      - LOG_ENABLED=true
    volumes:
      - /root/pds-data:/pds
