# documentation: https://ce.judge0.com/
# slogan: Judge0, where code happens.
# tags: code,run,compute
# logo: svgs/judge0.png
# port: 2358
x-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: "100M"

services:
  judge0:
    image: judge0/judge0:1.13.1
    privileged: true
    environment:
      - SERVICE_FQDN_JUDGE0_2358
      - REDIS_HOST=${COOLIFY_REDIS_HOST:-redis}
      - REDIS_PASSWORD=${SERVICE_PASSWORD_REDIS}
      - POSTGRES_HOST=${COOLIFY_POSTGRES_HOST:-postgres}
      - POSTGRES_DB=${COOLIFY_POSTGRES_DB:-judge0}
      - POSTGRES_USER=${COOLIFY_POSTGRES_USER:-judge0}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
      - AUTHZ_TOKEN=${SERVICE_PASSWORD_AUTHZ}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:2358/version"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    <<: *default-logging

  worker:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    privileged: true
    environment:
      - REDIS_HOST=${COOLIFY_REDIS_HOST:-redis}
      - REDIS_PASSWORD=${SERVICE_PASSWORD_REDIS}
      - POSTGRES_HOST=${COOLIFY_POSTGRES_HOST:-postgres}
      - POSTGRES_DB=${COOLIFY_POSTGRES_DB:-judge0}
      - POSTGRES_USER=${COOLIFY_POSTGRES_USER:-judge0}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
      - AUTHZ_TOKEN=${SERVICE_PASSWORD_AUTHZ}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "pgrep", "-f", "workers"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    <<: *default-logging

  postgres:
    image: postgres:16.2
    environment:
      - POSTGRES_DB=${COOLIFY_POSTGRES_DB:-judge0}
      - POSTGRES_USER=${COOLIFY_POSTGRES_USER:-judge0}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 20s
      retries: 10
    <<: *default-logging

  redis:
    image: redis:7.2.4
    command:
      - bash
      - -c
      - docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"
    environment:
      - REDIS_PASSWORD=${SERVICE_PASSWORD_REDIS}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 20s
      retries: 10
    <<: *default-logging

volumes:
  postgres-data:
