# documentation: https://github.com/maybe-finance/maybe
# slogan: Maybe: The OS for your personal finances.
# tags: finances,wallets,coins,stocks,investments,open,source
# logo: svgs/maybe.svg
# port: 3000

services:
  web:
    image: ghcr.io/maybe-finance/maybe:latest
    volumes:
      - app_storage:/rails/storage
    environment:
      - SERVICE_FQDN_MAYBE
      - SELF_HOSTED=true
      - RAILS_FORCE_SSL=${RAILS_FORCE_SSL:-false}
      - RAILS_ASSUME_SSL=${RAILS_ASSUME_SSL:-false}
      - SECRET_KEY_BASE=${SERVICE_BASE64_64_SECRETKEYBASE}
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://:${SERVICE_PASSWORD_REDIS}@redis:6379/1
      - OPENAI_ACCESS_TOKEN=${OPENAI_ACCESS_TOKEN}
      - POSTGRES_DB=${POSTGRES_DB:-maybe_production}
      - POSTGRES_USER=${SERVICE_USER_POSTGRES}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - "http://localhost:3000"

  worker:
    image: ghcr.io/maybe-finance/maybe:latest
    command: bundle exec sidekiq
    restart: unless-stopped
    environment:
      - SELF_HOSTED=true
      - RAILS_FORCE_SSL=${RAILS_FORCE_SSL:-false}
      - RAILS_ASSUME_SSL=${RAILS_ASSUME_SSL:-false}
      - SECRET_KEY_BASE=${SERVICE_BASE64_64_SECRETKEYBASE}
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB:-maybe_production}
      - POSTGRES_USER=${SERVICE_USER_POSTGRES}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
      - REDIS_URL=redis://:${SERVICE_PASSWORD_REDIS}@redis:6379/1
      - OPENAI_ACCESS_TOKEN=${OPENAI_ACCESS_TOKEN}
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "bundle", "exec", "rails", "runner", "puts 'OK'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s      
  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - maybe_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${SERVICE_USER_POSTGRES}
      - POSTGRES_DB=${POSTGRES_DB:-maybe_production}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    restart: unless-stopped
    command: redis-server --requirepass ${SERVICE_PASSWORD_REDIS}
    volumes:
      - maybe_redis_data:/data
    environment:
      - REDIS_PASSWORD=${SERVICE_PASSWORD_REDIS}
    healthcheck:
      test: ["CMD", "redis-cli", "auth", "${SERVICE_PASSWORD_REDIS}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
