# documentation: https://www.rivet.dev/docs
# slogan: Build and scale stateful workloads with long-lived processes
# category: development
# tags: stateful, actors, realtime, backend, serverless, postgresql
# logo: svgs/rivet.svg
# port: 6420

services:
  rivet-engine:
    image: rivetdev/engine:2.2.0
    environment:
      - SERVICE_URL_RIVET_6420
      - RIVET__FILE_SYSTEM__PATH=/data
      - 'RIVET__AUTH__ADMIN_TOKEN=${SERVICE_BASE64_TOKEN}'
    volumes:
      - 'rivet-data:/data'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - http://127.0.0.1:6420/health
      interval: 2s
      timeout: 10s
      retries: 10
      start_period: 30s