services:
  app:
    image: "snipe/snipe-it:v8.5.0"
    volumes:
      - "storage:/var/lib/snipeit"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SERVICE_URL_SNIPEIT_80
      - "APP_ENV=${APP_ENV:-production}"
      - "APP_DEBUG=${APP_DEBUG:-false}"
      - "APP_KEY=${APP_KEY:?base64:${SERVICE_REALBASE64_32_APPKEY}}"
      - "APP_URL=${SERVICE_URL_SNIPEIT}"
      - "APP_TIMEZONE=${APP_TIMEZONE:?UTC}"
      - "APP_LOCALE=${APP_LOCALE:?en-US}"
      - "MAX_RESULTS=${MAX_RESULTS:?500}"
      - "PRIVATE_FILESYSTEM_DISK=${PRIVATE_FILESYSTEM_DISK:-local}"
      - "PUBLIC_FILESYSTEM_DISK=${PUBLIC_FILESYSTEM_DISK:-local_public}"
      - "DB_CONNECTION=${DB_CONNECTION:-mysql}"
      - "DB_HOST=${DB_HOST:-db}"
      - "DB_SOCKET=${DB_SOCKET:-null}"
      - "DB_PORT=${DB_PORT:-3306}"
      - "DB_DATABASE=${DB_DATABASE:-snipeit}"
      - "DB_USERNAME=${DB_USERNAME:?${SERVICE_USER_MARIADB}}"
      - "DB_PASSWORD=${DB_PASSWORD:?${SERVICE_PASSWORD_64_MARIADB}}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?${SERVICE_PASSWORD_64_ROOT}}"
      - "DB_PREFIX=${DB_PREFIX:-null}"
      - "DB_DUMP_PATH=${DB_DUMP_PATH:-/usr/bin}"
      - "DB_DUMP_SKIP_SSL=${DB_DUMP_SKIP_SSL:-true}"
      - "DB_DUMP_SINGLE_TRANSACTION=${DB_DUMP_SINGLE_TRANSACTION:-false}"
      - "DB_CHARSET=${DB_CHARSET:-utf8mb4}"
      - "DB_COLLATION=${DB_COLLATION:-utf8mb4_unicode_ci}"
      - "DB_SSL=${DB_SSL:-false}"
      - "DB_SSL_IS_PAAS=${DB_SSL_IS_PAAS:-false}"
      - "DB_SSL_KEY_PATH=${DB_SSL_KEY_PATH:-null}"
      - "DB_SSL_CERT_PATH=${DB_SSL_CERT_PATH:-null}"
      - "DB_SSL_CA_PATH=${DB_SSL_CA_PATH:-null}"
      - "DB_SSL_CIPHER=${DB_SSL_CIPHER:-null}"
      - "DB_SSL_VERIFY_SERVER=${DB_SSL_VERIFY_SERVER:-null}"
      - "MAIL_MAILER=${MAIL_MAILER:?smtp}"
      - "MAIL_HOST=${MAIL_HOST:?null}"
      - "MAIL_PORT=${MAIL_PORT:?1025}"
      - "MAIL_USERNAME=${MAIL_USERNAME:?null}"
      - "MAIL_PASSWORD=${MAIL_PASSWORD:?null}"
      - "MAIL_TLS_VERIFY_PEER=${MAIL_TLS_VERIFY_PEER:?true}"
      - "MAIL_FROM_ADDR=${MAIL_FROM_ADDR:?you@example.com}"
      - "MAIL_FROM_NAME=${MAIL_FROM_NAME:?Snipe-IT}"
      - "MAIL_REPLYTO_ADDR=${MAIL_REPLYTO_ADDR:?you@example.com}"
      - "MAIL_REPLYTO_NAME=${MAIL_REPLYTO_NAME:?Snipe-IT}"
      - "MAIL_AUTO_EMBED_METHOD=${MAIL_AUTO_EMBED_METHOD:?attachment}"
      - "ALLOW_BACKUP_DELETE=${ALLOW_BACKUP_DELETE:-false}"
      - "ALLOW_DATA_PURGE=${ALLOW_DATA_PURGE:-false}"
      - "IMAGE_LIB=${IMAGE_LIB:?gd}"
      - "MAIL_BACKUP_NOTIFICATION_DRIVER=${MAIL_BACKUP_NOTIFICATION_DRIVER:-null}"
      - "MAIL_BACKUP_NOTIFICATION_ADDRESS=${MAIL_BACKUP_NOTIFICATION_ADDRESS:-null}"
      - "BACKUP_ENV=${BACKUP_ENV:-true}"
      - "SESSION_LIFETIME=${SESSION_LIFETIME:-12000}"
      - "EXPIRE_ON_CLOSE=${EXPIRE_ON_CLOSE:-false}"
      - "ENCRYPT=${ENCRYPT:-false}"
      - "COOKIE_NAME=${COOKIE_NAME:-snipeit_session}"
      - "COOKIE_DOMAIN=${COOKIE_DOMAIN:-null}"
      - "SECURE_COOKIES=${SECURE_COOKIES:-false}"
      - "API_TOKEN_EXPIRATION_YEARS=${API_TOKEN_EXPIRATION_YEARS:-40}"
      - "APP_TRUSTED_PROXIES=${APP_TRUSTED_PROXIES:-192.168.1.1,10.0.0.1,172.16.0.0/12}"
      - "ALLOW_IFRAMING=${ALLOW_IFRAMING:-false}"
      - "REFERRER_POLICY=${REFERRER_POLICY:-same-origin}"
      - "ENABLE_CSP=${ENABLE_CSP:-false}"
      - "CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-null}"
      - "ENABLE_HSTS=${ENABLE_HSTS:-false}"
      - "CACHE_DRIVER=${CACHE_DRIVER:-file}"
      - "SESSION_DRIVER=${SESSION_DRIVER:-file}"
      - "QUEUE_CONNECTION=${QUEUE_CONNECTION:-sync}"
      - "CACHE_PREFIX=${CACHE_PREFIX:-snipeit}"
      - "REDIS_HOST=${REDIS_HOST:-null}"
      - "REDIS_PASSWORD=${REDIS_PASSWORD:-null}"
      - "REDIS_PORT=${REDIS_PORT:-6379}"
      - "MEMCACHED_HOST=${MEMCACHED_HOST:-null}"
      - "MEMCACHED_PORT=${MEMCACHED_PORT:-null}"
      - "PUBLIC_AWS_SECRET_ACCESS_KEY=${PUBLIC_AWS_SECRET_ACCESS_KEY:-null}"
      - "PUBLIC_AWS_ACCESS_KEY_ID=${PUBLIC_AWS_ACCESS_KEY_ID:-null}"
      - "PUBLIC_AWS_DEFAULT_REGION=${PUBLIC_AWS_DEFAULT_REGION:-null}"
      - "PUBLIC_AWS_BUCKET=${PUBLIC_AWS_BUCKET:-null}"
      - "PUBLIC_AWS_URL=${PUBLIC_AWS_URL:-null}"
      - "PUBLIC_AWS_ENDPOINT=${PUBLIC_AWS_ENDPOINT:-null}"
      - "PUBLIC_AWS_PATH_STYLE=${PUBLIC_AWS_PATH_STYLE:-null}"
      - "PUBLIC_AWS_BUCKET_ROOT=${PUBLIC_AWS_BUCKET_ROOT:-null}"
      - "PRIVATE_AWS_ACCESS_KEY_ID=${PRIVATE_AWS_ACCESS_KEY_ID:-null}"
      - "PRIVATE_AWS_SECRET_ACCESS_KEY=${PRIVATE_AWS_SECRET_ACCESS_KEY:-null}"
      - "PRIVATE_AWS_DEFAULT_REGION=${PRIVATE_AWS_DEFAULT_REGION:-null}"
      - "PRIVATE_AWS_BUCKET=${PRIVATE_AWS_BUCKET:-null}"
      - "PRIVATE_AWS_URL=${PRIVATE_AWS_URL:-null}"
      - "PRIVATE_AWS_ENDPOINT=${PRIVATE_AWS_ENDPOINT:-null}"
      - "PRIVATE_AWS_PATH_STYLE=${PRIVATE_AWS_PATH_STYLE:-null}"
      - "PRIVATE_AWS_BUCKET_ROOT=${PRIVATE_AWS_BUCKET_ROOT:-null}"
      - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-null}"
      - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-null}"
      - "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-null}"
      - "LOGIN_MAX_ATTEMPTS=${LOGIN_MAX_ATTEMPTS:-5}"
      - "LOGIN_LOCKOUT_DURATION=${LOGIN_LOCKOUT_DURATION:-60}"
      - "RESET_PASSWORD_LINK_EXPIRES=${RESET_PASSWORD_LINK_EXPIRES:-900}"
      - "INVITE_PASSWORD_LINK_EXPIRES=${INVITE_PASSWORD_LINK_EXPIRES:-1500}"
      - "LOG_CHANNEL=${LOG_CHANNEL:-stderr}"
      - "LOG_MAX_DAYS=${LOG_MAX_DAYS:-10}"
      - "APP_LOCKED=${APP_LOCKED:-false}"
      - "APP_CIPHER=${APP_CIPHER:-AES-256-CBC}"
      - "APP_FORCE_TLS=${APP_FORCE_TLS:-false}"
      - "GOOGLE_MAPS_API=${GOOGLE_MAPS_API:-}"
      - "LDAP_MEM_LIM=${LDAP_MEM_LIM:-500M}"
      - "LDAP_TIME_LIM=${LDAP_TIME_LIM:-600}"
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - "http://localhost/health"
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: "mariadb:11.4.7"
    volumes:
      - "db_data:/var/lib/mysql"
    environment:
      - "MYSQL_DATABASE=${MYSQL_DATABASE:-snipeit}"
      - "MYSQL_USER=${MYSQL_USER:?${SERVICE_USER_MARIADB}}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD:?${SERVICE_PASSWORD_64_MARIADB}}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?${SERVICE_PASSWORD_64_ROOT}}"
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - "--connect"
        - "--innodb_initialized"
      interval: 5s
      timeout: 1s
      retries: 5
