# documentation: https://trilium.rocks/TnJosFkIKTvr
# slogan: Build your personal knowledge base with Trilium Notes
# tags: note-taking,markdown,pkm
# logo: svgs/trilium.svg
# port: 8080

services:
  trilium:
    image: zadam/trilium:0.60-latest
    environment:
      - SERVICE_FQDN_TRILIUM_8080
    volumes:
      - trilium-data:/home/node/trilium-data