# documentation: https://github.com/TriliumNext/Trilium
# slogan: Build your personal knowledge base with TriliumNext Notes.
# category: productivity
# tags: self-hosted, notes, todo, organize, markdown, wiki
# logo: svgs/triliumnext.svg
# port: 8080

services:
  triliumnext:
    image: ghcr.io/triliumnext/trilium:stable
    environment:
      - SERVICE_URL_TRILIUMNEXT_8080
      - TZ=${TZ:-Europe/Berlin}
    volumes:
      - triliumnext_data:/home/node/trilium-data
    healthcheck:
      test: ["CMD", "node", "/usr/src/app/docker_healthcheck.cjs"]
      interval: 5s
      timeout: 20s
      retries: 10
