# documentation: https://velld.vercel.app/docs
# slogan: Self-hosted database backup management with a beautiful web interface for scheduling, managing, and monitoring backups across PostgreSQL, MySQL, MongoDB, and Redis.
# tags: backup,database,postgresql,mysql,mongodb,redis,automation,self-hosted
# logo: svgs/velld.svg
# port: 3000

services:
  api:
    image: ghcr.io/dendianugerah/velld/api:sha-ce8b88c
    environment:
      - SERVICE_URL_API_8080=
      - JWT_SECRET=${SERVICE_HEX_32_JWT}
      - ENCRYPTION_KEY=${SERVICE_HEX_32_ENCRYPTION}
      - ADMIN_USERNAME_CREDENTIAL=${ADMIN_USERNAME_CREDENTIAL:-admin}
      - ADMIN_PASSWORD_CREDENTIAL=$SERVICE_PASSWORD_VELLDADMIN
      - ALLOW_REGISTER=${ALLOW_REGISTER:-false}
      - PORT=8080
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM=${SMTP_FROM}
    volumes:
      - api_data:/app/data
      - backup_data:/app/backups
    healthcheck:
      test: ["CMD", "wget", "--spider", "-qO-", "http://localhost:8080/health"]
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 10s

  web:
    image: ghcr.io/dendianugerah/velld/web:sha-ce8b88c
    environment:
      - SERVICE_URL_VELLD_3000=
      - NEXT_PUBLIC_API_URL=$SERVICE_URL_API # Needs to be accessible by a browser
      - ALLOW_REGISTER=${ALLOW_REGISTER:-false}
    depends_on:
      - api