# documentation: https://github.com/wg-easy/wg-easy
# slogan: The easiest way to run WireGuard VPN + Web-based Admin UI.
# tags: wireguard,vpn,web,admin
# logo: svgs/wireguard.svg
# port: 8000

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    environment:
      - SERVICE_FQDN_WIREGUARDEASY_8000
      - WG_HOST=${SERVICE_FQDN_WIREGUARDEASY}
      - PASSWORD_HASH=${SERVICE_PASSWORD_HASH_BCRYPT_WIREGUARDEASY}
      - LANG=${LANG:-en}
      - PORT=8000
      - WG_PORT=${WG_PORT:-51820}
      - WG_MTU=${WG_MTU:-1420}
      - WG_DEFAULT_ADDRESS=${WG_DEFAULT_ADDRESS:-10.8.0.x}
      - WG_DEFAULT_DNS=${WG_DEFAULT_DNS:-1.1.1.1}
      - WG_ALLOWED_IPS=${WG_ALLOWED_IPS:-0.0.0.0/0,::/0}
      - WG_PERSISTENT_KEEPALIVE=${WG_PERSISTENT_KEEPALIVE:-0}
      - WG_DEVICE=${WG_DEVICE:-eth0}
      
    volumes:
      - wg-easy:/etc/wireguard
    ports:
      - 51820:51820/udp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
