#!/usr/bin/env bash

# Inspired on https://github.com/adriancooney/Taskfile
#
# Install an alias, to be able to simply execute `run`
# echo 'alias run=./scripts/run' >> ~/.aliases
#
# Define Docker Compose command prefix...
set -e

docker compose &>/dev/null
if [ $? == 0 ]; then
    DOCKER_COMPOSE="docker compose"
else
    DOCKER_COMPOSE="docker-compose"
fi

function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}
function queue {
    bash vendor/bin/spin exec -u webuser coolify php artisan queue:listen
}
function reset-db {
    bash vendor/bin/spin exec -u webuser coolify php artisan migrate:fresh --seed
}
function coolify {g
    bash vendor/bin/spin exec -u webuser coolify bash
}
function coolify-root {
    bash vendor/bin/spin exec coolify bash
}
function vite {
    bash vendor/bin/spin exec vite bash
}

function default {
    help
}

TIMEFORMAT="Task completed in %3lR"
time "${@:-default}"
