name: Lock inactive threads

on:
  schedule:
    - cron: "0 1 * * *"

permissions:
  issues: write
  discussions: write
  pull-requests: write

concurrency:
  group: lock-threads
  cancel-in-progress: true

jobs:
  lock-threads:
    runs-on: ubuntu-24.04 # https://github.com/actions/runner-images
    steps:
      - name: Lock threads after 30 days of inactivity
        uses: dessant/lock-threads@7266a7ce5c1df01b1c6db85bf8cd86c737dadbe7 # https://github.com/dessant/lock-threads/releases/tag/v6.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-inactive-days: 30
          pr-inactive-days: 30
          discussion-inactive-days: 30
