{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coolify.fullname" . }}-worker
  labels:
    {{- include "coolify.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
  {{- with .Values.worker.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.worker.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "coolify.componentLabels" (dict "root" . "component" "worker") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "coolify.componentLabels" (dict "root" . "component" "worker") | nindent 8 }}
        {{- with .Values.worker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.worker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "coolify.serviceAccountName" . }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if and .Values.persistence.enabled .Values.storageInit.enabled }}
      initContainers:
        {{- include "coolify.storageInitContainer" . | nindent 8 }}
      {{- end }}
      containers:
        - name: worker
          image: {{ include "coolify.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /var/www/html
          command:
            {{- toYaml .Values.worker.command | nindent 12 }}
          args:
            {{- toYaml .Values.worker.args | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            {{- include "coolify.commonEnv" . | nindent 12 }}
            - name: HORIZON_ENABLED
              value: "true"
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          volumeMounts:
            {{- include "coolify.volumeMounts" . | nindent 12 }}
      volumes:
        {{- include "coolify.envVolume" . | nindent 8 }}
        {{- include "coolify.dataVolume" . | nindent 8 }}
{{- end }}
