{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "coolify.fullname" . }}-migrate
  labels:
    {{- include "coolify.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrate
  annotations:
    {{- if .Values.migration.hook }}
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    {{- end }}
    {{- with .Values.migration.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  backoffLimit: {{ .Values.migration.backoffLimit }}
  activeDeadlineSeconds: {{ .Values.migration.activeDeadlineSeconds }}
  template:
    metadata:
      labels:
        {{- include "coolify.componentLabels" (dict "root" . "component" "migrate") | nindent 8 }}
        {{- with .Values.migration.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.migration.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "coolify.serviceAccountName" . }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.migration.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.migration.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.migration.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.migration.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if and .Values.persistence.enabled .Values.storageInit.enabled }}
      initContainers:
        {{- include "coolify.storageInitContainer" . | nindent 8 }}
      {{- end }}
      containers:
        - name: migrate
          image: {{ include "coolify.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /var/www/html
          command:
            {{- toYaml .Values.migration.command | nindent 12 }}
          args:
            {{- toYaml .Values.migration.args | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            {{- include "coolify.commonEnv" . | nindent 12 }}
            - name: MIGRATION_ENABLED
              value: "true"
            - name: SEEDER_ENABLED
              value: {{ .Values.seeder.enabled | quote }}
          resources:
            {{- toYaml .Values.migration.resources | nindent 12 }}
          volumeMounts:
            {{- include "coolify.volumeMounts" . | nindent 12 }}
      volumes:
        {{- include "coolify.envVolume" . | nindent 8 }}
        {{- include "coolify.dataVolume" . | nindent 8 }}
{{- end }}
