{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "coolify.fullname" . }}
  labels:
    {{- include "coolify.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "coolify.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
        {{- with .Values.networkPolicy.ingressNamespaceLabels }}
        - namespaceSelector:
            matchLabels:
              {{- toYaml . | nindent 14 }}
        {{- end }}
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 6001
{{- end }}
