apiVersion: v1
kind: Service
metadata:
  name: {{ include "coolify.fullname" . }}
  labels:
    {{- include "coolify.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "coolify.componentLabels" (dict "root" . "component" "web") | nindent 4 }}
